#+TITLE: Methods in Constructing the CN Stellate Microcircuit
#+AUTHOR: Michael A Eager
#+DATE:
#+OPTIONS: toc:nil H:5 author:nil <:t >:t 
#+STARTUP: oddeven hideblocks fold align hidestars
#+TODO: REFTEX
#+LANGUAGE: en_GB

#+LATEX_HEADER:\graphicspath{{../SimpleResponsesChapter/gfx/}{../figures/}{/media/data/Work/cnstellate/}{/media/data/Work/cnstellate/ResponsesNoComp/ModulationTransferFunction/}}
#+LATEX_HEADER:\setcounter{secnumdepth}{5}
#+LATEX_HEADER:\lfoot{\footnotesize\today\ at \thistime}


#+BIBLIOGRAPHY: MyBib alphanat
#+LaTeX_CLASS: UoM-draft-org-article

## Write text after begin { document } 

\setcounter{chapter}{1}
\chapter{Methods}\label{sec:Ch2:Methods}


This chapter introduces the general methods used throughout this thesis.  More
specific description of the methods and procedures used is provided in the
relevant chapters.



## set global variables for in-code blocks 
* Prelude 							   :noexport:

#+begin_src emacs-lisp 
  (add-to-list 'org-export-latex-classes
               '("UoM-draft-org-article"
 "\\documentclass[11pt,a4paper,twoside,openright]{book}
  \\usepackage{../hg/manuscript/style/uomthesis}
  \\input{../hg/manuscript/user-defined}
  \\usepackage[acronym]{glossaries}
  \\input{../hg/manuscript/misc/glossary}
  \\makeglossaries
  \\pretolerance=150
  \\tolerance=100
  \\setlength{\\emergencystretch}{3em}
  \\overfullrule=1mm
 %%  \\usepackage[notcite]{showkeys}
  \\lfoot{\\footnotesize\\today\\ at \\thistime}
        [NO-DEFAULT-PACKAGES]
        [NO-PACKAGES]"
                 ("\\clearpage\\section{%s}" . "\n\\clearpage\\section{%s}")
                 ("\\subsection{%s}" . "\n\\clearpage\\subsection{%s}")
                 ("\\subsubsection{%s}" . "\n\\subsubsection{%s}")
                 ("\\paragraph{%s}" . "\n\\paragraph{%s}")
                 ("\\subparagraph{%s}" . "\n\\subparagraph{%s}")))
  (setq org-latex-to-pdf-process '("pdflatex -interaction nonstopmode %f" "makeglossaries %b" "bibtex %b"  "pdflatex -interaction nonstopmode %f"  "pdflatex -interaction nonstopmode %f" ))
  (setq org-export-latex-title-command "\\singlespacing{\\tableofcontents\\printglossaries}")
#+end_src

#+RESULTS:
: \singlespacing{\tableofcontents\printglossaries}


* Auditory Periphery Models 
  :PROPERTIES:
  :LABEL: sec:Ch2:Modelling
  :END:

To understand the auditory system, one must first understand the
transformations preceeding neural signals in the auditory
nerve. Mechanical vibrations at the eardrum (tympanic membrane) are
conducted by the middle ear bones to vibrations of fluid in the inner
ear (cochlea).

They are then transformed to chemical signals in the inner hair cells
and then to electrical potentials of the \ANFs.  The organisation of the
auditory system is described as 'tonotopic' after the continuous
logarithmic frequency tuning along the basilar membrane.  The \CF of
\ANFs is typical of the resonant frequency of the adjacent basilar membrane 
#\IHC 
and forms a topographical receptive field according to place along the
central auditory nervous system.  This processing enters an information
bottle-neck at the auditory nerve, who all terminate in the \CN.  At
this point, a group of highly specialised heterogeneous neurons in the
\CN process the incoming information in several feature-based
information pathways. These include the high temporal acuity pathway
(bushy cells), the onset detection pathway (octopus cells), the azimuth
detection pathway (pyramid cells of the DCN), and the robust and
enhanced spectral pathway (\TS cells).

# \yellownote{needs references and further expansion.
#   Introduce new acronyms and keywords here eg. tonotopic.  Be careful not to
#   reproduce stuff done in the results chapters }

# This processing also enters a bottle-neck at the auditory nerve,
#  selectivity), referred to as `tonotopy'

The population of \ANFs project to the \CN in a tonotopic fashion, bifurcate
after passing the central nervous system barrier to innervate the ventral and
dorsal portions of the cochlear nucleus \VCN and \DCN, Figure
\ref{fig:CochlearNucleus} \citep{Lorente:1981}.  Type I \ANFs are categorised into
\HSR and \LSR fibres. LSR
fibres have a higher threshold and do not saturate like HSR fibres. They also
project to the \GCD
\citep{RyugoParks:2003,RyugoHaenggeliEtAl:2003} along with the smaller,
unmyelinated type II ANFs, which suggests they play a different role in sound
processing to HSR fibres.

#+BEGIN_LaTeX
 \begin{figure}
 \begin{center}
  % \includegraphics[keepaspectratio=true]{Cat_Human_CN.jpg}
 \caption{Cochlear nucleus innervation in Man and Cat }
 \label{fig:CochlearNucleus}
 \end{center}
 \end{figure}
#+END_LaTeX


#  \begin{figure}
#  \begin{center}
#  \resizebox{5in}{!}{\includegraphics[keepaspectratio=true]{gfx/ZilanyBruceFig.JPG}}
#  \caption{Zilany and Bruce 2007 Auditory Periphery model}
#  \label{fig:ZilanyBruceFig}
#  \end{center}
#  \end{figure}

# \yellownote{a paragraph on the inner working of the AN model}

The auditory nerve inputs to the cochlear nucleus model neurons are
provided by phenomenological auditory periphery models: The ARLO model
\citep{HeinzZhangEtAl:2001} and the Bruce model
\citep{BruceSachsEtAl:2003,ZilanyBruce:2006,ZilanyBruce:2007}. The
ARLO model consists of an outer/middle ear pre-processing filter, a
cochlear filterbank, \IHC to \AN synapse model and dead-time modified
Poisson spike generator. \citep{HeinzZhangEtAl:2001} incorporated
cochlear filters based on the critical bandwidths obtained from
psychophysical experiments in humans. The ARLO model of the cat
auditory periphery, with non-linear compression and two-tone
suppression, was used in this study except in the vowel simulation
where the human auditory periphery model was used.

The \citet{ZilanyBruce:2007} model was enhanced by an additional signal
path and its predictions have matched a wide range of physiological
data in normal and impaired cat data.



# \medskip{}

# \yellownote{Discuss auditory model history. Expand reasons for wanting to create
#   a biophysically realistic model of the CN\@. Discuss reason for using whole
#   network in TV and TS optimisation}

# \medskip{}

# \yellownote{a paragraph on the history of AN modelling
#   \citep{LeakeSnyderEtAl:1993, ArnesenOsen:1978, CloptonWinfieldEtAl:1974}.
#   Perhaps Rose et al 1959 would be better suited here}

# 
# \medskip{}

# In examining the properties of a detailed neural model of the cochlear nucleus,
# a realistic and phenomenologically sound auditory model was needed to represent
# sounds and transformations that occur in the central auditory system.

# 
# \medskip{}

#* Auditory Nerve Fibre Models
# ** Phenomenological Auditory Periphery Models

The auditory nerve inputs to the cochlear nucleus model neurons are
provided by phenomenological auditory periphery models originating from
\citet{Carney:1993}. These include the ARLO model
\citet{HeinzZhangEtAl:2001}, the Bruce model
\citep{BruceSachsEtAl:2003,ZilanyBruce:2006,ZilanyBruce:2007}; and the
Zilany model \citep{ZilanyBruceEtAl:2009}. The \AN model consists of an
outer/middle ear pre-processing filter, a cochlea filterbank, \IHC to \AN
synapse model and dead-time modified Poisson spike generator, as shown
in Figure \ref{fig:ZilanyBruceFig}. \citep{HeinzZhangEtAl:2001}
incorporated cochlea filters based on the critical bandwidths obtained
from psycho\-physical experiments in humans. The ARLO model of the cat
auditory periphery, with non-linear compression and two-tone
suppression, was used in this study except in the vowel simulation where
the human auditory periphery model was used.  \yellownote{TODO: AN model
paragraph has been changed - fix any comment related to new Zilany}

# \medskip{}

The \citet{ZilanyBruce:2007} model improves the previous AN model by an
additional signal path and its predictions have matched a wide range of
physiological data in normal and impaired cat data. The most recent AN
model comprises an power-law synapse model, with internal $1/f$ noise,
that enhances the behaviour of long-term dependence in ANFs
\citep{ZilanyBruceEtAl:2009}.
Where possible, a cat model with normal hearing was used. Chapter \ref{sec:GAChapter} uses the ARLO model  \citep{HeinzZhangEtAl:2001}
and Chapters \ref{sec:Chapter3} and \ref{sec:Chapter4} use the Zilany model \citep{ZilanyBruceEtAl:2009,ZilanyCarney:2010}.
# \medskip{}

#  \yellownote{Why is it the cat model? updating Carney model?} Updating of the
#  Carney auditory model has led to the change in the model's configuration from an
#  original implementation of the rat model.  The default species is the cat and
#  will be used in the data presented in this chapter.

#  \begin{figure}[tbh]
#    \begin{center}
#  %    \resizebox{3.5in}{!}{\includegraphics[keepaspectratio=true]{NoFigure}}
#      \resizebox{\textwidth}{!}{\includegraphics[keepaspectratio=true]{gfx/ZilanyCarney-JASA-2009-Fig2.eps}}
#      \caption{Auditory periphery model with dual power-law synapse
#        \citep[originally printed in ][]{ZilanyBruceEtAl:2009}.}
#      \label{fig:ZilanyBruceFig}
#    \end{center}
#  \end{figure}\yellownote{if this figure is used it needs permission by the original authors}

# ** Range and Centre Frequencies of Network

# Auditory Model Parameters}  & Cat model, Normal Hearing    \citep{HeinzZhangEtAl:2001} \\ %\hline
# %       Greenwood function for cats   (Hz)     & See Eq.~\ref{eq:Meth:Greenwood}&\citep{Greenwood:1990} % $f=456.0\times 10^{\frac{x}{11.9} } -0.8$  & Basilar membrane position, $x$, and characteristic frequency, $f$, \citep{Greenwood:1990} \\ %\hline
#                 Low Freq. (kHz)                &                   0.2                 & \\ %\hline
#                High Freq. (kHz)                &                   30                  & \\ %\hline
#             Channels             &                     60                     & 

# Centre frequencies determined by Greenwood function \citep{Greenwood:1990} (See Eq.~\ref{eq:Meth:Greenwood}).


* Connectivity and Topology in Neural Microcircuits
   :PROPERTIES:
   :LABEL: sec:Ch2:ConnectivityandTopology
   :END:

Like many other neural complexes in the brain, the likelihood of
connectivity between two cells in the \CN is a function of distance,
cell type, and receptive-field spread. Connectivity between cells in a
post-synaptic group onto individual cells is described by a synaptic
weight, /w/, the number of synapses, /n/, and the spatial bandwidth,
$\sqrt{s}$, which were taken to be uniform for each connection type.
The allocation of pre-synaptic cells to post-synaptic cells was a random
process modeled here using a Gaussian function, with mean equal to the
post-synaptic cell's \CF channel and variance equal to
$s/2$. Topographical connectivity in this model was based on position
within the \CN (Figure \ref{fig:Meth:MicroCN}B), but is easily
interchangeable with frequency-specific connectivity.  Connection
parameters that are fixed are shown in Table \ref{tab:Meth:GeneralParams}
and parameters used in the optimization are shown in Table
\ref{tab:Meth:Genome}.

The basic unit of sensory networks is the place-channel or
feature-channel of the microcircuit, which separates the receptive field
into independent groups. The creation of neural microcircuits based on
``place'' is easily amenable to different sensory neural network models;
however there are problems and unique features that may be necessary to
ensure realistic representation of the system.  In the microcircuits and
networks presented in this thesis, it is the iso-frequency place-channel
that receives afferent input from the narrowest receptive field possible
in the auditory nerve model.

Connection variables between cell-types are generally uniform across
the network but may be adjusted to suit the model.  Model parameters
may be different between species or within species, therefore, without
adequate information regarding exact neuron to neuron connection
reasonable assumptions are made based on the average population data.
Issues arise at the ends of large-scale topographic BNNs with
overlapping place\slash channel connections.  Boundaries are
considered closed bookends, where post-synaptic neurons select only
from those with its connection range.  The best modelling behaviour
would arise, therefore, in the middle sections.



Figure~\ref{fig:MicrocircuitConn} shows the method for Gaussian spread of
connections between cell types used throughout this thesis.  
#  The channels are separated using the same Greenwood function as used for the AN filterbank.
#+BEGIN_LaTeX
  \begin{figure}[tbh]
    \begin{center}
  %    \resizebox{3.5in}{!}{\includegraphics[keepaspectratio=true]{NoFigure}}
       \resizebox{\textwidth}{!}{\includegraphics[keepaspectratio=true]{../SimpleResponsesChapter/gfx/CNConn}}
  %     \resizebox{0.8\textwidth}{!}{\input{./gfx/CNConn.tex}}
      \caption{Gaussian connection between cell types in cochlear
        nucleus.}
      \label{fig:MicrocircuitConn}
    \end{center}
  \end{figure}
#+END_LaTeX



Network parameters that control the connectivity between two
cell-type groups can be defined by: 
- $\mathbf{w}_{\textrm{{Pre}}\to\textrm{{Post}}}$ :: the synaptic weight of
     the post-synaptic current influx caused by the pre-cells'
     neurotransmitter activating the receptor channels of the
     post-synaptic cell.  This value may be either uniform for all
     synapses across the in this connection type or defined by a
     function of the receptive field.
- $\mathbf{n}_{\textrm{{Pre}}\to\textrm{{Post}}}$ :: the number of
     presynaptic cell type synapses onto individual cells in the
     post-synaptic cell type.
- $\mathbf{s}_{\textrm{{Pre}}\to\textrm{{Post}}}$ ::  the spatial or
     feature specific spread of connections from presynaptic cells onto
     post-synaptic cells.  The spread is the variance of a Gaussian
     probability distribution, $\mathcal{N}(i,\sqrt{s})$, representing
     the probability of the post-synaptic cell in position /i/ receiving
     input from a post-synaptic cell in the network's discrete slices;
     in this case frequency channels.  The spread variable is uniform
     across the stellate CN network.  A spread of 0 means all
     connections come from the same frequency channel, assuming no
     offset.
- $\mathbf{o}_{\textrm{{Pre}}\to\textrm{{Post}}}$ :: the offset in
     distribution of connections between presynaptic cell types and
     post-synaptic cell.  The offset variable adjusts the centre point
     of the probability distribution, $\mathcal{N}(i + o, \sqrt{s})$,
     away from the post-synaptic cell's position, /i/.
- $\mathbf{d}_{\textrm{{Pre}}\to\textrm{{Post}}}$ :: is the temporal delay
     between a pre-cells' AP trigger and the onset of the
     post-synaptic current.  This delay incorporates the axonal
     conduction delay and diffusion time across the synaptic cleft.

# New limitations of place-based connectivity

Auditory nerve projections to each \CN cell-type share the same synaptic
weight, $w_{{\mathrm{ANF}\to\mathrm{CN}}}$, but \HSR and \LSR fibers have
different parameters encoding the number of inputs
($n_{{\mathrm{HSR}\to\mathrm{P}}}$, $n_{_{\mathrm{HSR}\to\mathrm{P}}}$). \ANFs
with similar characteristic frequencies are spatially organized into
$N_{\textrm{Channel}}$ iso-frequency lamina or channels.

\TS and \TV cells' dendrites are located within isofrequency lamina, so
synapses are chosen from fibres in the channel ($s=0$, see Table
\ref{tab:Meth:GeneralParams}). \DS cells have many arborizations extending
perpendicular to \ANF axons and have a typical physiological responses
to frequencies 2 octaves below and 1 octave above their \CF
\citep{PalmerJiangEtAl:1996,PaoliniClark:1999} (see fixed parameters in
Table \ref{tab:Meth:GeneralParams}).  Physiological evidence in the golgi
cell domain of the ventral \CN shows that neurons have monotonic,
non-saturating rate-level curves, similar to \LSR \ANFs
\citep{GhoshalKim:1996a}. \ANF labeling evidence shows the absence of
\HSR \ANFs in the Golgi cell domain of the \CN
\citep{Liberman:1991,Ryugo:2008,RhodeOertelEtAl:1983}, so the strength
of Golgi excitation was given by \wLSRGLG and \nLSRGLG. Wide-band
inhibition of \TV cells by \DS cells includes an additional channel
offset, \oDSTV, to account for the asymmetry of wideband suppression
found in \TV cells \citep{ReissYoung:2005}.  The offset was added to the
Gaussian mean in the random allocation process.

The connectivity of the cell types involved in the stellate microcircuit
is shown in Figure \ref{fig:microcircuit} and in Table
\ref{tab:TSModelSummary}iii. Fast, glycinergic inhibition from \TV cells
and \DS cells (Figure \ref{fig:microcircuit}) is involved in modulating
the firing rate and spike interval variability in \TS cells
\citep{FerragamoGoldingEtAl:1998,WickesbergOertel:1993}. \TV cells in
the deep layer of the dorsal \CN, provide a delayed narrowband
inhibition to \TS and \DS cells in the ventral \CN.  The dendrites of
\DS cells cover 1/3 of the cross-frequency axis in the \CN, contributing
to this cell's wide frequency response. In turn this cell is responsible
for altering the frequency responses in \TS and \TV cells
\citep{SpirouDavisEtAl:1999}.  \DS cells are coincidence detectors and
have a precisely timed onset response that affects the temporal
properties of \TS cells
\citep{PaoliniClareyEtAl:2005,RhodeGreenberg:1994a} and completely
inhibit \TV cell responses to loud clicks
\citep{SpirouDavisEtAl:1999}. GABAergic inhibition from Golgi cells
modulates the level of excitation necessary to reach threshold for all
\CN cells \citep{CasparyBackoffEtAl:1994,FerragamoGoldingEtAl:1998}.
Feedback circuits from the olivary complex to the ventral \CN are also
known to use \GABA as a neurotransmitter \citep{SaintMorestEtAl:1989},
however this was not included in this model.



* Stellate Microcircuit Model of the Cochlear Nucleus

** Simulation Environment

Neural models and network connections were generated using the neural
simulation package [[latex:progname][NEURON]] \citep{CarnevaleHines:2006}. NMODL, an
extension of [[latex:progname][NEURON]] \citep{HinesCarnevale:2000}, was used to implement
membrane current models and interface with the auditory nerve
model. Numerical integration was performed using the Crank-Nicholson
method with second order accuracy (in [[latex:progname][NEURON]] $secondorder=2$) and fixed
time step of either 0.1  or 0.05 ms. 


The computations of the NEURON model were distributed on a single
PC; a cluster of nine PCs (3.0 GHz Intel Pentium4);[fn::  Systems
provided by the Department of Otolaryngology, the University of
Melbourne] an SGI Altix system (=soma=: 64 32-bit Itanium
CPUs);[fn::  System =soma= provided by the Neuroimaging Group and
Department of Electrical and Electronic Engineering, the University of
Melbourne] or on an iDataPlex IBM system (=merri=: 1024 64-bit Intel
x86 CPUs).[fn::  Sytem =merri= provided by the Victorian Life Sciences
Computing Initiative]


The parallel capabilities of the network model presented in Chapter
\ref{sec:Chapter3} were based on the NEURON network model [[latex:progname][netmod]] (see
other neural models that also use =netmod= at [[http://modeldb.senselab.yale.edu][ModelDB]], particularly
models [[http://senselab.med.yale.edu/senselab/modeldb/ShowModel.asp?model=52034][52034]], [[http://senselab.med.yale.edu/senselab/modeldb/ShowModel.asp?model=2730][2730]], and [[http://senselab.med.yale.edu/senselab/modeldb/ShowModel.asp?model=51781][51781]] \citet{MiglioreCanniaEtAl:2006}) .
Genetic algorithms and sensitivity analysis in Chapter
\ref{sec:GAChapter} were implemented in [[latex:progname][C++]] using [[http://lancet.mit.edu/ga][GAlib]]
\citep{Wall:2006} and the parallel virtual machine PVM libraries
\citep{GeistBeguelinEtAl:1994}.

#The random numbers are required throughout this thesis in .
#generator used was the internal RNG of NEURON, MCellRand4


** Stimulus Generation

In order to emulate sound entering the ear, acoustic sounds were generated to be
passed in to an auditory model.  The acoustic stimulus was generated in [[latex:progname][NEURON]],
with the exception of notch noise (which was generated in [[latex:progname][MATLAB/GNU
Octave]]). The stimulus types included pure tones, white noise, sinusoidal
amplitude modulated sounds and clicks.

# The first run of a stimulus may take some time if the AN responses have not been previously saved.  
The AN model described in \citet{ZilanyBruce:2007} requires a sampling
rate of 500 kHz in the stimulus.  The output of the AN model was then
down-sampled to a lesser resolution for the spike generator and saved
for further use.  The resolution of the spike generator was generally at
10 or 20 kHz to match the simulations' time step of 0.1 or 0.05 ms.
Version 4 of the AN model \citep{ZilanyBruceEtAl:2009} was sampled at
100 kHz for \CF units below 20 kHz, otherwise a sampling rate of 200 kHz
was used.

Chapter \sec{sec:GAChapter} and the optimisation of \DS cell connections
to \TV cells (see Section \ref{sec:Ch3:DSTV} in Chapter
\ref{sec:Chapter3}) use notch noise as the stimulus.  Notch noise was
generated from Gaussian white noise filtered using a stop-band filter in
[[latex:progname][MATLAB/GNU Octave]].  The notch noise sample was stored in a file so that
it could be retrieved by NEURON in the simulation.

#  with a
# 50 kHz sampling frequency and filtered with a quarter octave, 30 dB
# band-stop, 100-tap FIR filter centered at 5 kHz. A 50 ms stimulus was
# presented at 60 dB \SPL with 5 ms onset/offset ramps, a 20 ms delay and
# 10 ms pause after the stimulus. Notch noise stimuli have been used in
# experimental studies of the \CN to measure the asymmetric, wide-band
# suppression of \TV cells by \DS cells \citep{ReissYoung:2005} and to
# estimate the frequency range of \ANFs converging on \DS cells
# \citep{PalmerJiangEtAl:1996}.
 



** Cochlear Nucleus Stellate Microcircuit

The tonotopic organisation of the auditory pathway (i.e.\space the
continuous mapping of sound frequency to place of resonance in the
cochlea) is transferred to the \CN through the population of \ANFs
\citep{Lorente:1981}.  The \CN stellate network model drawn in Figure
\ref{fig:microcircuit} describes the following cells and models:
1. Auditory nerve fibres :: The base line in Figure
     \ref{fig:microcircuit} is a simplification of \ANFs from low \CF to
     high \CF (left to right).  The model reproduces responses for high
     and low \SR \ANFs at a fixed number of frequency channels across the auditory range of the species being studied.
2. Golgi cells :: A \GABA-ergic \VCN marginal shell unit is assumed
     to regulate excitability in the \GCD and core \VCN units
     \citep{FerragamoGoldingEtAl:1998}.  Only one /in vivo/ study has
     recorded extracellular data in the marginal shell area of the \CN
     \citep{GhoshalKim:1997}.  The presumed characteristics of Golgi
     cells are taken from that study and are defined by a monotonic
     response to tones and noise, and an unusual or chopper \PSTH.
3. D stellate cells :: A glycinergic, large multipolar cell with \OnC
     \PSTH response that acts as a coincidence detector.  Its large
     dendritic area increases its response to noise allowing it to
     behave as a wide-band inhibitor in the \VCN, \DCN, and
     contralateral \CN
     \citep{SmithMassieEtAl:2005,ArnottWallaceEtAl:2004,NeedhamPaolini:2007}.
4. Tuberculoventral cells :: A glycinergic, type II \EIRA unit in the
     deep layer of the \DCN \citep{SpirouDavisEtAl:1999}.  This cell
     acts as a delayed echo-suppressor and narrow-band inhibitor, with
     recurrent connections between D and T stellate cells in the \VCN
     \citep{Alibardi:2006,OertelWickesberg:1993,WickesbergWhitlonEtAl:1991}.
5. T stellate cells :: One of the major output projection cells of
     the \CN to the inferior colliculus.  This multipolar neuron has
     been shown to have robust spectral representation and enhanced
     synchronisation to modulation in speech sounds
     \citep{BlackburnSachs:1990,KeilsonRichardsEtAl:1997}.



** Auditory Model

The input auditory model used in this thesis provides the major
phenomenological qualities of experimentally recorded \ANFs. The Zilany
model \citep{ZilanyBruceEtAl:2009} was based on many auditory models from
the Carney Lab
\citep{HeinzColburnEtAl:2001,ZhangCarney:2001,Carney:1993}. The centre
frequencies for 100 channels is determined by the logarithmic Greenwood
function \citep{Greenwood:1990} of the basilar membrane in cats. The
model reproduces responses for 50 high and 30 low \SR \ANFs in each
frequency channel, across the frequency range 200 Hz to 64 kHz.



# ** Golgi Cell Model
# Inputs to Golgi cells are more complicated than the inputs to core \VCN
# neurons.  Golgi cells are sparse in the region surrounding the \VCN
# called the granule cell domain.  Extracellular recordings from labelled
# Golgi cells are not available in the literature; however, the \GCD (or
# marginal shell of the \VCN in cats) has been studied in only one study
# without direct labelling of recorded units \citep{GhoshalKim:1997}.  Any
# extracellular spikes recorded in the \GCD are most likely from Golgi
# cells since granule cell somata are less than 10 \um and their narrow
# axons are unlikely to elicit electrical activity in the electrodes.  The
# majority of recorded units showed a monotonic increase in firing rate
# with increasing sound intensity \citep{GhoshalKim:1997}.
# The Golgi cell model is implemented as an instantaneous-rate Poisson
# rate model.  The primary inputs are from the auditory model's
# instantaneous rate outputs with connections across frequency channels.
# \HSR and \LSR \ANF inputs to Golgi cells were specified by a Gaussian
# distribution in fibres across the network.  The weighted sum of \HSR and
# \LSR instantaneous-rate vectors were smoothed out by an alpha function
# mimicking a synaptic and dendritic smoothing filter.


# * Neural Models
#   :PROPERTIES:
#   :LABEL: sec:NeuralModels
#   :END:





# *** Conductance  Neural Models

# Hodgkin-Huxley-like

# \yellownote{Include discussion on HH-like neural models}

# Input resistance was calculated using [[latex:progname][NEURON]]'s /Impedence/ class by setting the input current frequency to 0 Hz[fn:: See input resistance function =rn()= in Appendix \ref{sec:Apdx:Utilities}.].





** Auditory Nerve Model

The input to the stellate microcircuit was provided by the
phenomenological auditory nerve model of \citet{HeinzZhangEtAl:2001} and
originally developed by Carney and colleagues
\citep{Carney:1993,ZhangCarney:2001}. The model reproduces all
significant auditory nerve phenomena including non-linear compression
and two-tone suppression over a wide range of frequencies in the normal
hearing cat model, for an extensive review of existing auditory models
see \citet{Lopez-Poveda:2005}. The range and number of frequency
channels in the auditory filterbank was defined in each of the proceeding
chapters and depends on the level of spatial resolution required in the
network models; however, increases in frequency channel greatly
increases the computational load and simulation time in the AN and CN
models.

Center frequencies of the channels were spaced logarithmically according to the
basilar membrane frequency-place map function, Equation
\ref{eq:Meth:Greenwood}, called the Greenwood function
\citep{Greenwood:1990}:
\begin{equation} \label{eq:Meth:Greenwood} 
f(x) = A \left(10^{ax/L} - k\right) \quad (Hz)
\end{equation} 
\noindent where /x/ is the distance along the basilar
membrane from the stapes, and variables /A/, /a/, /L/, and /k/ are dependent on the species.
The data listed in Table \ref{tab:Ch2:Greenwood} shows the currently accepted
parameters for each species.

# \citep{FitzGeraldBurkittEtAl:2001}

# after \\: \hline or \cline{col1-col2} \cline{col3-col4} ...
#+caption: [Basilar membrane frequency-distance function parameters]{Frequency to basilar membrane distance function parameters. Data obtained from \url{http://earlab.bu.edu}.}
#+label: tab:Ch2:Greenwood
|                       |    *A* |   *a* |       *k* |  *L* |
|-----------------------+--------+-------+-----------+------|
| Human ^{\footnotesize 1} |  165.4 |   2.1 | 1.0(0.88) |   35 |
| Cat   ^{\footnotesize 2} |    456 |   2.1 |       0.8 |   25 |
| Rat  ^{\footnotesize 3}  | 7613.3 | 0.928 |       1.0 | 8.03 |
#+latex: {\footnotesize{$^1$ \citet{Greenwood:1990}, $^2$ \citet{Liberman:1982}, $^3$ \citet{Muller:1991}}}



*** High and Low Spontaneous Rate ANFs

The level of spontaneous activity and minimum thresholds in \ANFs are
separated into two distinct groups, \HSR and \LSR fibres.  The \SR of
\HSR and \LSR was set to 50 and 0.5 Hz, respectively.
Twenty \HSR and ten \LSR \AN fibers were simulated
for each frequency-channel.
The stimulus was passed through the auditory nerve model for each
frequency channel for both \LSR and \HSR fibers, producing an
instantaneous firing rate response that was down sampled to 10 kHz.

# ** Point Process Neural Models 

The neural models used in the auditory nerve fibres (and the Golgi cell model in Chapters \ref{sec:Chapter3}-\ref{sec:Chapter4}) are
inhomogeneous Poisson processes. The instantaneous rate is passed through the
Jackson model, which includes refractory effects typical of the auditory nerve
fibres \citep{Jackson:2003,JacksonCarney:2005}.  Spike trains for each neuron in
the model are created at the start of each repetition of the stimulus, but can
be saved and loaded from file to improve efficiency.




Spike times were generated independently for each fibre from the
instantaneous firing rate using a pseudo-random Poisson spike-generator
\citep{Jackson:2006,JacksonCarney:2005}, with refractory effects similar to those
present in \ANFs.  The double exponential relative refractory functions,
specific to ANFs, were:
\begin{eqnarray} 
y_0(t) = c_0*exp(-(t'-t_{\textrm{a}})/s_0) \\ 
y_1(t) = c_1*exp(-(t'-t_{\textrm{a}})/s_1) 
\end{eqnarray} 
\noindent where /t'/ is the time relative to the last
spike, $c_0 = 0.5$, $c_1 = 0.5$, $s_0 = 0.001$ ms, and $s_1 = 0.0125$
ms.  The absolute refractory period, $t_{\textrm{a}}$, was 0.75 ms.
Improvements in the spike-generation method 





# \yellownote{Para: Notes from Hegger: discuss poisson generator} 
# # $$r(t) = \alpha [V(t)-V_{\mathrm th}]$$ 
# where 
# # $$\mathrm{P}\left{ n \mathrm{spike during}  (t_1,t_2)\right} = e^{\langle{}n\rangle}\frac{(\langle{}n\rangle)^n}{n!} \approx r(t)\delta{}t$$ then refractory effects; then renewal process PDF
# \begin{equation}  
# p(\tau) = (\kappa{}r)^{\kappa} \tau^{\kappa-1} e^{-\kappa{} r \tau} / (\kappa - 1)! 
# \end{equation}

# \yellownote{Real neuronal spike generation is highly reliable and deterministic, as has been demonstrated by countless numbers of \textit{in vitro} studies. }

# Complex time-varying currents, injected into neurons in rat cortex
# slices, resulted in spike trains were reproducible across repeats to
# less than 1 msec \citep{MainenSejnowski:1995}.  The noise in
# \textit{in vivo} neural responses is believed to result from the fact
# that synapses are very unreliable. In fact, greater than half of the
# arriving presynaptic nerve impulses fail to evoke a postsynaptic
# response \citep[e.g.,~][]{AllenStevens:1994}. The noise in the synapses,
# not in the spike generator!



# \yellownote{discuss ANF SR, types of ANF, long-term dependence, and
#   standard results of spiking models, and how Jackson then Zilany
#   have tried to fit these to the AN data}


# Analysis of the frequency
#  response area of ANF generates known parameters for each fibre, these are:
#  \begin{itemize} 
#  \item the spontaneous rate (SR), generated in silence and is
#    categoried into two groups High SR ($>$18 sp/s) and Low SR ($<$ 18
#    sp/s);
#  \item threshold, the sound pressure level(SPL) at which the cell
#    responds above the spontaneous rate
#  \item characteristic frequency (CF)
#  \end{itemize}

# \medskip{}



** Rothman and Manis Neural Cell Models
  :PROPERTIES:
  :LABEL: sec:Meth:cell-models
  :END:

\HH single compartment conductance models
\citep{HodgkinHuxley:1952a} were used to model the cochlear nucleus
cells. The dynamics of the membrane voltage, $V(t)$, is described by:
\begin{equation} \label{eq:Meth:V} 
C_{m} \frac{dV}{dt} = - \gleak (V - \Eleak) - \INa - \IKHT - \IKLT - \IKA - \Ih - \sum \ISYN
\end{equation} \noindent where $C_{m}$ is the specific membrane
capacitance, \gleak is the specific leak conductance with associated
leak reversal potential \Eleak, \INa is the sodium current density,
\IKHT, \IKLT, \IKA are three types of potassium current densities, \Ih
is a hyperpolarization-activated current density, and \ISYN are synaptic
input current densities.  The potassium and mixed-cation current models
used here come from an investigation of isolated ventral \CN cells
\citep{RothmanManis:2003,RothmanManis:2003a,RothmanManis:2003b}, which
yielded accurate mathematical descriptions of (subsequent variables are
defined in Table \ref{tab:Meth:GeneralParams}):
 - the high-threshold rectifying potassium current
   density: 
\begin{equation} \label{eq:Meth:IKHT} 
\IKHT(t,V)= \gKHT (\varphi n^{2} + (1-\varphi ) p)(V - \EK ) 
\end{equation}
 - the fast-activating transient potassium current
  density: 
\begin{equation} \label{eq:Meth:IKA} 
\IKA(t,V)=\gKA a^{4} b c (V -  \EK) 
\end{equation}
 - the low-threshold, fast-activating, slowly-deactivating potassium
   current density: and 
\begin{equation} \label{eq:Meth:IKLT}
   \IKLT(t,V)=\gKLT w^{3} z (V-\EK) 
\end{equation}
 - the mixed-cation hyperpolarization-activated current
   density.  
\begin{equation} \label{eq:Meth:Ih} 
\Ih(t,V)=\gh r (V-\Eh) 
\end{equation}

The form of the \HH sodium current was:
\begin{equation} \label{eq:Meth:INa} 
\INa(t,V)=\gNa m^{3} h (V - \ENa)
\end{equation} \noindent where the active voltage-dependant current
densities \INa, \IKHT, \IKLT, \IKA and \Ih, and each of their activation
and deactivation functions (/a, b, c, h, m, n, p, r, w/ and /z/) are
described in detail by \citet{RothmanManis:2003} and the [[latex:progname][NEURON]] source
code is freely available online at [[http://senselab.med.yale.edu/senselab/modeldb][ModelDB]] \citep{HinesMorseEtAl:2004}.

All simulations in this thesis were performed at 37\degC. Temperature scaling of
each current's activation and deactivation time constant parameters was
calculated with $Q_{10}=3.0$.  Maximum conductance parameters, $\bar{g}$, were
adjusted with temperature coefficient $Q_{10}=2.0$, except for \Ih which has
temperature coefficient $Q_{10}=1.3$.


Table \ref{tab:Meth:CellTypes} shows the maximum conductances, $\bar{g}$,
for each cell type in the network.  The neurons in the ventral \CN
differ in their composition of these currents on the basis of their
current-clamp type. They are classified as either type I or type II
based on their response to intracellular current injection
\citep{OertelWuEtAl:1988}. The response of type I neurons to current
injection is regularly spaced \APs. \TV \citep{ZhangOertel:1993b} and
Golgi cells \citep{FerragamoGoldingEtAl:1998a} are classic type I, and
have \INa, \IKHT and \Ih currents. While \TS cells are type I, they have
additional A-type transient potassium channels, \IKA
\citep{FerragamoGoldingEtAl:1998,RothmanManis:2003b}. Type II responses
have only one phasic \AP at the start of the stimulus, characteristic of
ventral \CN bushy cells, which enables them to rapidly follow \ANF input
events \citep{OertelWuEtAl:1988,SmithRhode:1989}. \IKLT is present in
type-II units and is active at resting membrane potential, which allow
for rapid changes depending on the input. \DS cells respond with a
single \AP for injected current levels near threshold, then discharge
regularly for higher current levels
\citep{OertelWuEtAl:1988,PaoliniClark:1999}, corresponding to an
intermediate type I-II response. \DS cells have a small amount of \IKLT
current to reduce the cells input resistance and enhance coincidence
detection.  The membrane parameters were fixed after we established the
/in vitro/ characteristics of each cell type from the literature
\citep{FerragamoGoldingEtAl:1998,FerragamoGoldingEtAl:1998a,OertelWuEtAl:1988,ZhangOertel:1993b}
at 37\degC, and matched them to the model types in
\citet{RothmanManis:2003}.

#+BEGIN_LaTeX
  \begin{table}[tp]
    \centering
    \caption{Cell-type Membrane Current Parameters}\label{tab:Meth:CellTypes}
    \begin{tabularx}{0.8\linewidth}{lcccc}\toprule
             Cells            &  \TS   &  \DS   &   \TV   & Golgi \\ %\hline
      Current Clamp Model     &  I-t   &  I-II  &   I-c   & I-c \\[0.5ex] \midrule
       \gNa, S/cm$^{2}$       & 0.235  & 0.235  &  0.235  & 0.235 \\ %\hline
       \gKHT, S/cm$^{2}$      & 0.018  &  0.02  &  0.019  & 0.019 \\ %\hline
       \gKLT, S/cm$^{2}$      &   0    & 0.0047 &    0    & 0 \\ %\hline
       \gKA, S/cm$^{2}$       & 0.0153 &   0    &    0    & 0 \\ %\hline
       \gh, mS/cm$^{2}$       & 0.0618 & 0.247  & 0.06178 & 0.6178 \\ %\hline
      \gleak, mS/cm$^{2}$     & 0.471  & 0.471  &  0.471  & 0.962 \\ %\hline
      Soma Diameter, \um      &   21   &   25   &  19.5   & 15 \\ %\hline
  Input Resistance, M$\Omega$ &  163   &   73   &   170   & 130 \\ 
  \bottomrule
  \end{tabularx}
  \end{table}
#+END_LaTeX


** Synapse Models
   :PROPERTIES:
   :LABEL: sec:Ch2:Synapse
   :END:
Synapses were modeled with either a single or a double exponential
time-dependent conductance change with the current density described by
$\ISYN(t)=g_{{\rm SYN}} (t)(V-E_{{\rm rev}} )$, where $E_{\rm rev}$ is the
associated reversal potential. 
[[latex:progname][NEURON]]'s conductance synapse model classes /ExpSyn/ and /Exp2Syn/ were used
in the \CN stellate microcircuit.  

The strength of the synapses was
determined by a normalized weight parameter, /w/, and decay
time-constants as follows:
\begin{eqnarray}
\label{eq:Meth:11} g_{{\rm Exc}} (t) = w_{{\rm Exc}} {\rm exp}(-t/\tau _{{\rm Exc}} ) \quad (\uS) \\
\label{eq:Meth:12} g_{{\rm Inh}} (t) = w_{{\rm Inh}} \eta \left({\rm exp}(-t/\tau_{{\rm Inh2}} )-{\rm exp}(-t/\tau _{{\rm Inh1}} )\right) \quad (\uS) 
\end{eqnarray} \noindent where $\eta$ normalizes the peak of the
double-exponential function to one (see Table
\ref{tab:Meth:GeneralParams}). 

Excitatory inputs to \CN cells from type-I \ANF terminals were mediated
by fast glutamatergic-\AMPA receptors
\citep{Gardner:2000,GardnerTrussellEtAl:1999}. \EPSPs in \VCN neurons
had a decay time constant of $\tAMPA = 0.36$ ms, whereas \TV cells in
the \DCN had a decay time constant of $\tAMPA = 0.40$ ms
\citep{GardnerTrussellEtAl:1999}.  The reversal potential of excitatory
synapse was 0 mV. 

Double exponential inhibitory
synapses are used in the network from glycinergic and GABAergic
neurons. Glycinergic inhibitory synapses are modeled from glycinergic \IPSPs
recorded in mature \CN and \MNTB neurons, which have a fast rise time,
$\tGlyone = 0.4$ msec, and a decay time constant $\tGlytwo = 2.5$ ms
\citep{AwatramaniTurecekEtAl:2005,HartyManis:1998,LeaoOleskevichEtAl:2004,LimOleskevichEtAl:2003}.
\GABAa synapses were modeled from \MNTB recordings in mature guinea pigs
\citep{AwatramaniTurecekEtAl:2005}.  \GABAa receptor currents have a
fast (9 ms) and a slow (150 ms) decay component
\citep{AwatramaniTurecekEtAl:2005,DavisYoung:2000}, but for short
stimuli only the fast component was modeled ($\tGABAone =0.7$ msec,
$\tGABAtwo =9.0$ ms). Chlorine reversal potential in Glycine and \GABAa
receptors was set to -75 mV


** Delay and Latency


The delay function in the \AN model was derived from 
\citet{CarneyYin:1988} in cats. The formula for the latency of acoustic stimulation to reach a
particular point on the basilar membrane comprises a fixed conduction
delay plus an additional delay that is an exponential function of the
distance from the stapes.  In the cat, \citet{CarneyYin:1988} fitted
the latency vs \CF curve from click responses in the cat to obtain the
equation:
\begin{equation} \label{eq:Meth:delay} 
d=A_{0} \exp(-x/A_{1})\times 10^{- 3} - 1/{\mathrm{f}_x},
\end{equation} 
\noindent where /x/ is the distance along the basilar membrane from the apex, $f_x$ is
the \CF (Hz) at this location, and constants $A_0$
and $A_1$ are 8.3 ms and 6.49 cm for cats, respectively.

# In humans, the delay function is:
# \begin{equation} \label{eq:delayhumans} 
# d(x) = 4.915 + 0.3631 \times \exp(0.11324 \times x),\quad 5\, <\, x\, <\, 35 \quad (\mathrm{mm})
# \end{equation} 
# \citet{HeinzZhangEtAl:2001} corrected the peak click to
# match the onset delay of ANFs, where $A_0 = 3.0$, $A_1 = 12.5$ and
# this has been retained in the model used here
# \citep{ZilanyBruceEtAl:2009}.

Synaptic transmission delay between neurons is typically measured in
experiments to be 0.5 ms. Axonal conductance between ventral
and dorsal \CN neurons, measured using electric shocks, is about 1.0 ms
\citep{WickesbergOertel:1993}.
\yellownote{Needs reference, and what about
Bahlmer and Lagner's 0.4 ms delays}

An additional AN delay is required that combines the AN model delay and the
effective axonal conductance to the CN neurons.
Mean first spike latency to click stimuli is used in Section \ref{sec:Ch3:Delay} used to set
delay times between \ANFs and \CN cells \citep{EagerGraydenEtAl:2006}.  The
delay was defined using the first spike latency of high frequency units as the
sum of the \ANFs' first spike latency, \ANF conduction delay, and the synaptic
transmission delay.
\yellownote{My citation here is from ANS 2006.  }






* Optimisation Techniques
  :PROPERTIES:
  :LABEL: sec:Ch2:Optimisation
  :END:


It still remains a laborious task to develop an accurate representation
of complex behaviour of real neural networks.  Pre-eminent computational
neuroscientists have noted that "choices, assumptions, and guesses" are
an integral part of neuronal modelling \citep{SegevBurkeEtAl:1998}.  With
the acceleration of computational power and enhanced experimental
techniques in multi-unit recordings are enabling more detailed neural
models to be developed.  There is much to be gained from
biophysically-realistic modelling approaches, especially in the
thoroughly investigated cochlear nucleus of mammals, bats and birds.

# \yellownote{See neural detail in auditory
# system\citep{LuRubioEtAl:2008}} \yellownote{Discuss use of Poisson
# models vs HH-like models.  Discuss single cell simulation vs whole
# network simulation during optimisation.}

To develop and optimise detailed neural models and neural network
models, reproducible research methods are required.  Examples of
parameter estimation and fitting in neural models are also becoming
more advanced, for example [[latex:progname][SSNS]] \citep{SichtigSchafferEtAl:2008},
[[latex:progname][NeuroFitter]] \citep{VanAchardEtAl:2007} and [[latex:progname][MultiRunFitter]] (a feature
in NEURON).  In this chapter, a table method introduced by
\citet{NordlieGewaltigEtAl:2009} is used to summarise the neural
models used in each optimisation step.  The Nordlie tables shown in
each optimisation stage consist of A) the model summary, B) cell type
populations, C) connectivity between two cell types, D) neuron and
synapse models, and E) optimisation parameters.  This method aims to
show a consistent and recognisable format for presenting various
neural network models and their constituents.

# \yellownote{this needs more explanation in the methods sections}

The standard methods for optimisation can be simply described with the
following steps:
 1. specify the function or model we want to optimise,
 2. specify the criteria we want to satisfy,
 3. specify the parameters that will be adjusted, and any constraints on
    those parameters, and finally
 4. perform the optimization.


** Simple Methods

Hand-tuning and gradient-decent optimisation is common in realistic
neural and network models.
In attempting to create a realistic microcircuit from a wide range of experimental data, Chapter \ref{sec:Chapter3} develops a parameter optimisation routine in sequential
stages.  The network parameters were chosen in the sequential optimisation stages
to encompass synaptic inputs to each individual cell type in the CN stellate microcircuit.


In developing and simulating the detailed neural models and neural network
models, a reproducible research method was used. The Nordlie approach
to reproducible neural network simulations
\citep{NordlieGewaltigEtAl:2009} is followed in Table
\ref{tab:ModelSummary}.  Tables \ref{tab:TSModelSummary}i through
\ref{tab:ModelSummary}v show the detailed summary of the \CN stellate
microcircuit used in the simulations performed in Chapter \ref{sec:Chapter3}.  

#+LATEX: \input{../MethodsChapter/NordlieTemplate}


** Evolutionary Methods

\yellownote{simple introduction to GAs, most of this stuff is done in Chapter \ref{sec:GAChapter}}



#+BEGIN_LaTeX
  \ifthenelse{\isundefined{\manuscript}}{\newpage\singlespacing\bibliographystyle{plainnat} \bibliography{../hg/manuscript/bib/MyBib}\newpage \listoftodos}{}
#+END_LaTeX



### Local Variables:
### mode: org
### mode: visual-line
### fill-column: 72
### End:

