#+TITLE: Methods in constructing the CN Stellate Microcircuit
#+AUTHOR: Michael A Eager
#+DATE:
#+OPTIONS: toc:nil H:5 author:nil <:t >:t 
#+STARTUP: oddeven hideblocks fold align hidestars
#+TODO: REFTEX

#+LANGUAGE: en_GB
#+LATEX_HEADER:\graphicspath{{./}{./gfx/}{../SimpleResponsesChapter/gfx/}{../figures/}{/media/data/Work/cnstellate/}{/media/data/Work/cnstellate/ResponsesNoComp/ModulationTransferFunction/}}
#+LATEX_HEADER:\setcounter{secnumdepth}{5}
#+LATEX_HEADER:\lfoot{\footnotesize\today\ at \thistime}
#+LATEX_HEADER:\usepackage{transparent}

#+BIBLIOGRAPHY: MyBib alphanat
#+LaTeX_CLASS: UoM-draft-org-article

## Write text after begin { document } 
#+TEXT: \singlespacing{\tableofcontents\printglossaries}
\setcounter{chapter}{2}
\chapter{Methods}\label{chp:Methods}

## set global variables for in-code blocks 

* Prelude 							   :noexport:

#+begin_src emacs-lisp results: silent
  (setq org-latex-to-pdf-process '("pdflatex -interaction nonstopmode %f" "makeglossaries %b" "bibtex %b"  "pdflatex -interaction nonstopmode %f"  "pdflatex -interaction nonstopmode %f" ))
  (setq org-export-latex-title-command "\singlespacing{\tableofcontents\printglossaries}")
  
  (add-to-list 'org-export-latex-classes
               '("UoM-draft-org-article"
 "\\documentclass[10pt,a4paper,twoside,openright]{book}
  \\usepackage{../hg/manuscript/style/uomthesis}
  \\input{../hg/manuscript/user-defined}
  \\usepackage[acronym]{glossaries}
  \\input{../hg/manuscript/misc/glossary}
  \\makeglossaries
  \\graphicspath{{./gfx/}}
  \\pretolerance=150
  \\tolerance=100
  \\setlength{\\emergencystretch}{3em}
  \\overfullrule=1mm
  % \\usepackage[notcite]{showkeys}
  \\lfoot{\\footnotesize\\today\\ at \\thistime}
  \\usepackage{rotating,calc}
  \\usepackage{booktabs,ltxtable,lscape}
        [NO-DEFAULT-PACKAGES]
        [NO-PACKAGES]"
                 ("\\clearpage\\section{%s}" . "\n\\clearpage\\section{%s}")
                 ("\\subsection{%s}" . "\n\\clearpage\\subsection{%s}")
                 ("\\subsubsection{%s}" . "\n\\subsubsection{%s}")
                 ("\\paragraph{%s}" . "\n\\paragraph{%s}")
                 ("\\subparagraph{%s}" . "\n\\subparagraph{%s}")))
#+end_src


* Modeling the Cochlear Nucleus Stellate Microcircuit

#+LABEL: fig:microcircuit
#+CAPTION [Cochlear nucleus stellate microcircuit]{Cochlear nucleus stellate microcircuit. Each cell type is shown with its response area (frequency (F) vs sound level (L)) and peri-stimulus time histogram (PSTH).  Synapse types:    Excitatory (open triangle), glycinergic (closed circle), and    GABAergic (closed rectangle). } 
[[file:./gfx/CNcircuit.pdf]]

** Cochlear Nucleus Stellate Microcircuit

The tonotopic organisation of the auditory pathway (i.e.\space the continuous
mapping of sound frequency to place of resonance in the cochlea) is transferred
to the \CN through the population of \ANFs \citep{Lorente:1981}.  The \CN
stellate network model drawn in Figure \ref{fig:microcircuit} describes the
following cells and models:
1.  Auditory nerve fibres :: The base line in Figure \ref{fig:microcircuit} is a
     simplification of \ANFs from low \CF to high \CF (left to right).  The
     model reproduces responses for high and low \SR \ANFs at 100 channels
     across the frequency range 200 Hz to 48 kHz.
2. The Golgi cell :: A \GABA-ergic \VCN marginal shell unit is assumed to regulate
     excitability in the \GCD and core \VCN
     units \citep{FerragamoGoldingEtAl:1998}.  Only one /in vivo/ study has
     recorded extracellular data in the marginal shell area of the \CN
     \citep{GhoshalKim:1997}.  The presumed characteristics of Golgi cells are
     taken from that study and are defined by a monotonic response to tones and
     noise, and an unusual or chopper \PSTH.
3. The D stellate cell :: A glycinergic, large multipolar cell with \OnC \PSTH
     response that acts as a coincidence detector.  Its large dendritic area
     increases its response to noise allowing it to behave as a wide-band
     inhibitor in the \VCN, \DCN, and contralateral \CN
     \citep{SmithMassieEtAl:2005,ArnottWallaceEtAl:2004,NeedhamPaolini:2007}.
4. The Tuberculoventral cell :: A glycinergic, type II \EIRA unit in the deep
     layer of the \DCN \citep{SpirouDavisEtAl:1999}.  This cell acts as a
     delayed echo-suppressor and narrow-band inhibitor, with recurrent
     connections between D and T stellate cells in the \VCN
     \citep{Alibardi:2006,OertelWickesberg:1993,WickesbergWhitlonEtAl:1991}.
5. The T stellate cell :: One of the major output projection cells of the \CN to
     the inferior colliculus.  This multipolar neuron has been shown to have
     robust spectral representation and enhanced synchronisation to modulation
     in speech sounds \citep{BlackburnSachs:1990,KeilsonRichardsEtAl:1997}.

To develop and simulate detailed neural models and neural network models,
reproducible research methods are required. The Nordlie approach to reproducible
neural network simulations \citep{NordlieGewaltigEtAl:2009} is followed in Table
\ref{tab:TSModelSummary}.  Tables \ref{tab:TSModelSummary}i through
\ref{tab:TSModelSummary}v show the detailed summary of the \CN stellate
microcircuit used in the \AM simulations.  The Nordlie table format splits the
tables into Model Summary, Populations, Connectivity, Neuron Model, and
Input\slash Output \citep{NordlieGewaltigEtAl:2009}.

\input{NordlieTemplate}

** Auditory Model

The input auditory model used in this paper provides the major phenomenological
qualities of experimentally recorded \ANFs. The Zilany model
\citep{ZilanyBruceEtAl:2009} is based on many auditory models from the Carney
Lab \citep{HeinzColburnEtAl:2001,ZhangCarney:2001,Carney:1993}. The centre
frequencies for 100 channels is determined by the logarithmic Greenwood function
\citep{Greenwood:1990} of the basilar membrane in cats. The model reproduces
responses for 50 high and 30 low \SR \ANFs in each frequency channel, across the
frequency range 200 Hz to 64 kHz.

** Golgi Cell Model

Inputs to Golgi cells are more complicated than the inputs to core \VCN neurons.
Golgi cells are sparse in the region surrounding the \VCN called the granule
cell domain.  Extracellular recordings from labelled Golgi cells are not
available in the literature; however, the \GCD (or marginal shell of the \VCN in
cats) has been studied by one group \citep{GhoshalKim:1997} without direct
labelling of recorded units.  Any extracellular spikes recorded in the \GCD are
most likely from Golgi cells since granule cell somata are less than 10 \um
and their narrow axons are unlikely to elicit electrical activity in the
electrodes.  The majority of recorded units showed a monotonic increase in
firing rate with increasing sound intensity \citep{GhoshalKim:1997}.

The Golgi cell model is implemented as an instantaneous-rate Poisson rate model.
The primary inputs are from the auditory model's instantaneous rate outputs with
connections across frequency channels.  \HSR and \LSR \ANF inputs to Golgi cells
were specified by a Gaussian distribution in fibres across the network.  The
weighted sum of \HSR and \LSR instantaneous-rate vectors were smoothed out by an
alpha function mimicking a synaptic and dendritic smoothing filter.


** Neural Models

The spiking neural models used in the auditory nerve fibres and Golgi cell model
are inhomogeneous Poisson processes.  The instantaneous rate is passed through
the Jackson spiking model, which includes refractory effects typical of the
auditory nerve fibres \citep{Jackson:2003,JacksonCarney:2005}.  Spike trains for
each neuron in the model are created at the start of each repetition of the
stimulus, but can be saved and loaded from a file.


Membrane current models (Table \ref{tab:TSModelSummary}iv) used in \DS, \TV and
\TS cell models were developed from kinectic analysis of \VCN neurons in mice
\citep{RothmanManis:2003b}. Their activation and deactivation functions (/a, b,
c, h, m, n, p, r, w/ and /z/) are described in detail by Rothman and Manis
\citep{RothmanManis:2003} and the [[latex:progname][NEURON]] source code is freely available online
at ModelDB \citep{HinesMorseEtAl:2004}.  Table \ref{tab:Celltypes2} shows the
membrane conductance parameters of the cell types.  Conductance parameters were
adjusted from \citep{RothmanManis:2003b} due to temperature and soma diameter
changes.
#  Rothman and Manis used 22$^\circ$C slice preparation.
#  Temperature effects the activation and deactivation functions'
#  time constants of the current models that used 37$^\circ$C. The
#  temperature quotient, Q=Q$_{10}^{((37^\circ -22^\circ )/10)}$,
#  was used to adjust the current models where Q$_{10}=3.0$
#  
The reversal potential for potassium, sodium, leak, and Ih currents were -72,
0, -65, and -43 mV, respectively.



#+LABEL: tab:Celltypes2
#+ATTR_LaTeX :align=l|ccc placement=[t!]\footnotesize
#+CAPTION: Cell-type Membrane Current Parameters
| Cells                           |    \TS |    \DS |     \TV |
| Current Clamp Model             |    I-t |   I-II |     I-c |
|---------------------------------+--------+--------+---------|
| \gNa ,\hfill S/cm^{2}              |  0.235 |  0.235 |   0.235 |
| \gKHT,\hfill S/cm^{2}              |  0.018 |   0.02 |   0.019 |
| \gKLT,\hfill S/cm^{2}              |      0 | 0.0047 |       0 |
| \gKA,\hfill S/cm^{2}               | 0.0153 |      0 |       0 |
| \gh,\hfill  mS/cm^{2}              | 0.0618 |  0.247 | 0.06178 |
| \gleak,\hfill mS/cm^{2}            |  0.471 |  0.471 |   0.471 |
| Soma Diameter,\hfill \um        |     21 |     25 |    19.5 |
| Input Resistance,\hfill M\Omega |    163 |     73 |     170 |

** Synapse Parameters

[[latex:progname][NEURON]]'s conductance synapse models, /ExpSyn/ and /Exp2Syn/, were used in the \CN
stellate microcircuit.  Single exponential excitatory synapses (\tAMPA = 0.36
ms) model the experimental recordings in \VCN neurons
\citep{GardnerTrussellEtAl:1999}.  Double exponential inhibitory synapses are
used in the network from glycinergic and GABAergic neurons. Glycinergic
synapses \citep{LeaoOleskevichEtAl:2004} (\tGlyone=0.4 ms and \tGlytwo=2.5 ms)
and \GABAa synapses \citep{AwatramaniTurecekEtAl:2005} (\tGABAone=0.7 ms and
\tGABAtwo=9.0 ms) were modeled from \MNTB neurons in mature guinea pigs.
Chlorine reversal potential in Glycine and \GABAa receptors was set to -75 mV
and excitatory reversal potential was set to 0 mV.



** Simulation Environment

Neural models and network connections were generated using the neural
simulation package [[latex:progname][NEURON]] \citep{CarnevaleHines:2006}. NMODL, an
extension of [[latex:progname][NEURON]] \citep{HinesCarnevale:2000}, was used to implement
membrane current models and interface with the auditory nerve
model. Numerical integration was performed using the Crank-Nicholson
method with second order accuracy (in [[latex:progname][NEURON]] $secondorder=2$) and fixed
time step of 0.1 ms. Genetic algorithms and sensitivity analysis were
implemented in [[latex:progname][C++]] using [[http://lancet.mit.edu/ga][GAlib]] \citep{Wall:2006} and the parallel
virtual machine libraries \citep{GeistBeguelinEtAl:1994}. \GA
simulations were distributed on a cluster of nine PCs (3GHz Pentium4)
and a 64-CPU SGI Altix with a master-slave paradigm.


** Stimulus Generation

For all simulations, frozen notch noise was used as the stimulus. Notch noise is
white noise that has been filtered by a narrow band-stop filter. Gaussian white
noise was generated in [[latex:progname][MATLAB/GNU Octave]] with a 50 kHz sampling frequency and
filtered with a quarter octave, 30 dB band-stop, 100-tap FIR filter centered at
5 kHz. A 50 ms stimulus was presented at 60 dB \SPL with 5 ms onset/offset
ramps, a 20 ms delay and 10 ms pause after the stimulus. Notch noise stimuli
have been used in experimental studies of the \CN to measure the asymmetric,
wide-band suppression of \TV cells by \DS cells \citep{ReissYoung:2005} and to
estimate the frequency range of \ANFs converging on \DS cells
\citep{PalmerJiangEtAl:1996}.

** Auditory Nerve Model

The input to the stellate microcircuit was provided by the
phenomenological auditory nerve model of \citet{HeinzZhangEtAl:2001} and
originally developed by Carney and colleagues
\citep{Carney:1993,ZhangCarney:2001}. The model reproduces all
significant auditory nerve phenomena including non-linear compression
and two-tone suppression over a wide range of frequencies in the normal
hearing cat model, for an extensive review of existing auditory models
see \citet{Lopez-Poveda:2005}. The auditory filterbank used in this
study consisted of sixty frequency channels with center frequencies
between 0.2 and 30 kHz, with other simulation parameters as listed in
Table \ref{tab:GA:GeneralParams}. Center frequencies of the channels
were spaced logarithmically according to the basilar membrane
frequency-place map of cats \citep[See Table ]{Greenwood:1990}.
\begin{equation} \label{eq:GA:Greenwood} 
f(x) = 456.0 \times 10^{\frac{x}{11.9} } - 0.8, \quad (Hz)
\end{equation}
\noindent where /x/ is the distance in centimeters from the apex.


The level of spontaneous activity in \HSR and \LSR \AN fibers was set to
50 and 0.5 Hz, respectively. The stimulus was passed through the
auditory nerve model for each frequency channel for both \LSR and \HSR
fibers, producing an instantaneous firing rate response that was down
sampled to 10 kHz. Twenty \HSR and ten \LSR \AN fibers were simulated
for each frequency-channel. Spike times were generated independently for
each fiber from the instantaneous firing rate using a pseudo-random
spike-generator \citep{JacksonCarney:2005}, with refractory effects
similar to those present in \ANFs.

** Stellate Microcircuit Model of the Cochlear Nucleus

*** Cell Models
  :PROPERTIES:
  :LABEL: sec:GA:cell-models
  :END:
\HH single compartment conductance models
\citep{HodgkinHuxley:1952a} were used to model the cochlear nucleus
cells. The dynamics of the membrane voltage, $V(t)$, is described by:
\begin{equation} \label{eq:GA:5} 
C_{m} \frac{dV}{dt} = - \gleak (V - \Eleak) - \INa - \IKHT - \IKLT - \IKA - \Ih - \sum \ISYN
\end{equation} 
\noindent where $C_{m}$ is the specific membrane capacitance, \gleak is the
specific leak conductance with associated leak reversal potential
\Eleak, \INa is the sodium current density, \IKHT, \IKLT, \IKA are three
types of potassium current densities, \Ih is a
hyperpolarization-activated current density, and \ISYN are synaptic
input current densities.  The potassium and mixed-cation current models
used here come from an investigation of isolated ventral \CN cells
\citep{RothmanManis:2003,RothmanManis:2003a,RothmanManis:2003b}, which
yielded accurate mathematical descriptions of (subsequent variables are
defined in Table \ref{tab:GA:GeneralParams}):
- the high-threshold rectifying potassium current density:
  \begin{equation} \label{eq:GA:6} 
\IKHT(t,V)= \gKHT (\varphi n^{2} + (1-\varphi ) p)(V - \EK )
  \end{equation}
- the fast-activating transient potassium current density:
  \begin{equation} \label{eq:GA:7} 
\IKA(t,V)=\gKA a^{4} b c (V - \EK)
  \end{equation}
- the low-threshold, fast-activating, slowly-deactivating
  potassium current density: and
  \begin{equation} \label{eq:GA:8} 
\IKLT(t,V)=\gKLT w^{3} z (V-\EK)
  \end{equation}
- the mixed-cation hyperpolarization-activated current density.
  \begin{equation} \label{eq:GA:9} 
\Ih(t,V)=\gh r (V-\Eh )
  \end{equation}

The form of the \HH sodium current was:
\begin{equation} \label{eq:GA:10} 
\INa(t,V)=\gNa m^{3} h (V - \ENa)
\end{equation}
\noindent where the active voltage-dependant current densities
\INa, \IKHT, \IKLT, \IKA and
\Ih, and each of their activation and deactivation functions
(/a, b, c, h, m, n, p, r, w/ and /z/) are described in
detail by \citet{RothmanManis:2003} and the [[latex:progname][NEURON]] source code is
freely available online at [[http://senselab.med.yale.edu/senselab/modeldb][ModelDB]] \citep{HinesMorseEtAl:2004}.

Table \ref{tab:GA:CellTypes} shows the maximum conductances,
$\bar{g}$, for each cell type in the network.  The neurons in the
ventral \CN differ in their composition of these currents on the basis
of their current-clamp type. They are classified as either type I or
type II based on their response to intracellular current injection
\citep{OertelWuEtAl:1988}. The response of type I neurons to current
injection is regularly spaced \APs. \TV
\citep{ZhangOertel:1993b} and Golgi cells
\citep{FerragamoGoldingEtAl:1998a} are classic type I, and have
\INa, \IKHT and \Ih currents. While
\TS cells are type I, they have additional A-type transient potassium
channels, \IKA \citep{FerragamoGoldingEtAl:1998,RothmanManis:2003b}. Type
II responses have only one phasic \AP at the start of the stimulus,
characteristic of ventral \CN bushy cells, which enables them to
rapidly follow \ANF input events
\citep{OertelWuEtAl:1988,SmithRhode:1989}. \IKLT is present
in type-II units and is active at resting membrane potential, which
allow for rapid changes depending on the input. \DS cells respond with
a single \AP for injected current levels near threshold, then discharge
regularly for higher current levels
\citep{OertelWuEtAl:1988,PaoliniClark:1999}, corresponding to an
intermediate type I-II response. \DS cells have a small amount of
\IKLT current to reduce the cells input resistance and
enhance coincidence detection.  The membrane parameters were fixed
after we established the /in vitro/ characteristics of each
cell type from the literature
\citep{FerragamoGoldingEtAl:1998,FerragamoGoldingEtAl:1998a,OertelWuEtAl:1988,ZhangOertel:1993b}
at 37\degC, and matched them to the model types in
\citet{RothmanManis:2003}.


#+BEGIN_LaTeX
  \begin{table}[tp]
    \centering
    \caption{Cell-type Membrane Current Parameters}\label{tab:GA:CellTypes}
    \begin{tabularx}{0.8\linewidth}{lcccc}\toprule
             Cells            &  \TS   &  \DS   &   \TV   & Golgi \\ %\hline
      Current Clamp Model     &  I-t   &  I-II  &   I-c   & I-c \\[0.5ex] \midrule
       \gNa, S/cm$^{2}$       & 0.235  & 0.235  &  0.235  & 0.235 \\ %\hline
       \gKHT, S/cm$^{2}$      & 0.018  &  0.02  &  0.019  & 0.019 \\ %\hline
       \gKLT, S/cm$^{2}$      &   0    & 0.0047 &    0    & 0 \\ %\hline
       \gKA, S/cm$^{2}$       & 0.0153 &   0    &    0    & 0 \\ %\hline
       \gh, mS/cm$^{2}$       & 0.0618 & 0.247  & 0.06178 & 0.6178 \\ %\hline
      \gleak, mS/cm$^{2}$     & 0.471  & 0.471  &  0.471  & 0.962 \\ %\hline
      Soma Diameter, \um      &   21   &   25   &  19.5   & 15 \\ %\hline
  Input Resistance, M$\Omega$ &  163   &   73   &   170   & 130 \\ 
  \bottomrule
  \end{tabularx}
  \end{table}
#+END_LaTeX


*** Synapse Models

Synapses were modeled with either a single or a double exponential
time-dependent conductance change with the current density described
by $\ISYN(t)=g_{{\rm SYN}} (t)(V-E_{{\rm rev}} )$, where
$E_{\rm rev}$ is the associated reversal potential. The strength of
the synapses was determined by a normalized weight parameter, /w/, and
decay time-constants as follows:
\begin{eqnarray}
\label{eq:GA:11} g_{{\rm Exc}} (t) = w_{{\rm Exc}} {\rm exp}(-t/\tau _{{\rm Exc}} ) \quad (\uS) \\
\label{eq:GA:12} g_{{\rm Inh}} (t) = w_{{\rm Inh}} \eta \left({\rm exp}(-t/\tau_{{\rm Inh2}} )-{\rm exp}(-t/\tau _{{\rm Inh1}} )\right) \quad (\uS) 
\end{eqnarray} \noindent where $\eta$ normalizes the peak of the
double-exponential function to one (see Table
\ref{tab:GA:GeneralParams}). Excitatory inputs to \CN cells from type-I
\ANF terminals were mediated by fast glutamatergic-\AMPA receptors with
a decay time constant of $\tAMPA = 0.36$ ms
\citep{Gardner:2000,GardnerTrussellEtAl:1999}, and the reversal
potential was 0 mV. We used the values from glycinergic currents
recorded in mature \CN neurons, which have a fast rise time, $\tGlyone =
0.4$ msec, and a decay time constant $\tGlytwo = 2.5$ ms
\citep{AwatramaniTurecekEtAl:2005,HartyManis:1998,LeaoOleskevichEtAl:2004,LimOleskevichEtAl:2003}.
Measured values in \GABAA receptor currents in \CN cells have a fast (9
ms) and a slow (150 ms) decay component
\citep{AwatramaniTurecekEtAl:2005,DavisYoung:2000}, but for short
stimuli only the fast component was modeled ($\tGABAone =0.7$ msec,
$\tGABAtwo =9.0$ ms).


*** Delay and Latency

The delay function in the \AN model was
derived from the work of \citet{CarneyYin:1988} in cats and defined as:
\begin{equation} \label{eq:GA:delay} 
d=A_{0} \exp(-x/A_{1})\times 10^{- 3} -1/f,
\end{equation} \noindent where /x/ is the distance along the basilar
membrane, /f/ is the characteristic frequency (Hz) at this location, and
constants $A_0$ and $A_1$ are 8.3 ms and 6.49 cm, respectively. 

Mean first spike latency to short \CF tones and click stimuli were used to set delay
times between \ANFs and \CN cells \citep{EagerGraydenEtAl:2006}. The delay was
defined using the first spike latency of high frequency units as the sum of the
\ANFs' first spike latency, \ANF conduction delay, and the synaptic transmission
delay.  The first spike latency measured in high \CF units in the ARLO \AN model
\citep{HeinzZhangEtAl:2001} for \HSR fibers was 1.5 ms.  Synaptic transmission
delay between adjacent neurons is typically measured in experiments to be 0.5
ms. The delay between ventral and dorsal \CN neurons is 1.0 ms
\citep{WickesbergOertel:1993}.  The additional delay from the \ANF to each cell
type was calculated to be \TS 1.6ms \citep{RhodeSmith:1986}, \DS 1.2 ms
\citep{RhodeOertelEtAl:1983}, \TV 2.0 ms \citep{SpirouDavisEtAl:1999}, and Golgi
2.3 ms \citep{FerragamoGoldingEtAl:1998a} to ensure the first spike latency
matched the experimental data.


** Connectivity

Like many other neural complexes in the brain, the likelihood of connectivity
between two cells in the \CN is a function of distance, cell type, and
receptive-field spread. Connectivity between cells in a post-synaptic group onto
individual cells is described by a synaptic weight, /w/, the number of synapses,
/n/, and the spatial bandwidth, $\sqrt{s}$, which were taken to be uniform for
each connection type.  The allocation of pre-synaptic cells to post-synaptic
cells was a random process modeled here using a Gaussian function, with mean
equal to the post-synaptic cell's \CF channel and variance equal to
\frac{s}{2}. Topographical connectivity in this model was based on position
within the \CN (Figure \ref{fig:GA:MicroCN}B), but is easily interchangeable
with frequency-specific connectivity.  Connection parameters that are fixed are
shown in Table \ref{tab:GA:GeneralParams} and parameters used in the
optimization are shown in Table \ref{tab:GA:Genome}.

Auditory nerve projections to each \CN cell-type share the same synaptic
weight, $w_{{\rm ANF}}$, but \HSR and \LSR fibers have different parameters
encoding the number of inputs ($n_{{\rm HSR}}$, $n_{{\rm LSR}}$). \ANFs with
similar characteristic frequencies are spatially organized into 60
iso-frequency lamina or channels. 

\TS and \TV cells' dendrites are
located within isofrequency lamina, so synapses are chosen from fibres
in the channel ($s=0$, see Table \ref{tab:GA:GeneralParams}). \DS cells
have many arborizations extending perpendicular to \ANF axons and have a
typical physiological responses to frequencies 2 octaves below and 1
octave above their \CF \citep{PalmerJiangEtAl:1996,PaoliniClark:1999}
(see fixed parameters in Table \ref{tab:GA:GeneralParams}).
Physiological evidence in the golgi cell domain of the ventral \CN shows
that neurons have monotonic, non-saturating rate-level curves, similar
to \LSR \ANFs \citep{GhoshalKim:1996a}. \ANF labeling evidence shows the
absence of \HSR \ANFs in the Golgi cell domain of the \CN
\citep{Liberman:1991,Ryugo:2008,RhodeOertelEtAl:1983}, so the strength
of Golgi excitation is given by \wLSRGLG and \nLSRGLG. Wide-band
inhibition of \TV cells by \DS cells includes an additional channel
offset, \oDSTV, to account for the asymmetry of wideband suppression
found in \TV cells \citep{ReissYoung:2005}.  The offset was added to the
Gaussian mean in the random allocation process.


The connectivity of the cell types involved in the stellate microcircuit is
shown in Figure \ref{fig:microcircuit} and in Table
\ref{tab:TSModelSummary}iii. Fast, glycinergic inhibition from \TV cells and \DS
cells (Figure \ref{fig:microcircuit}) is involved in modulating the firing rate
and spike interval variability in \TS cells
\citep{FerragamoGoldingEtAl:1998,WickesbergOertel:1993}. \TV cells in the deep
layer of the dorsal \CN, provide a delayed narrowband inhibition to \TS and \DS
cells in the ventral \CN.  The dendrites of \DS cells cover 1/3 of the
cross-frequency axis in the \CN, contributing to this cell's wide frequency
response. In turn this cell is responsible for altering the frequency responses
in \TS and \TV cells \citep{SpirouDavisEtAl:1999}.  \DS cells are coincidence
detectors and have a precisely timed onset response that affects the temporal
properties of \TS cells \citep{PaoliniClareyEtAl:2005,RhodeGreenberg:1994a} and
completely inhibit \TV cell responses to loud clicks
\citep{SpirouDavisEtAl:1999}. GABAergic inhibition from Golgi cells modulates
the level of excitation necessary to reach threshold for all \CN cells
\citep{CasparyBackoffEtAl:1994,FerragamoGoldingEtAl:1998}.  Feedback circuits
from the olivary complex to the ventral \CN are also known to use \GABA as a
neurotransmitter \citep{SaintMorestEtAl:1989}, however this is not included in
this model.


